-- Favorite Vehicles System Database Setup
-- Run this in your PostgreSQL database

-- 1. Create the favorites table
CREATE TABLE IF NOT EXISTS public.favorite_vehicles (
    favorite_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    vehicle_id INTEGER NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    priority INTEGER DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
    last_viewed TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    price_watch BOOLEAN DEFAULT TRUE,
    UNIQUE(account_id, vehicle_id)
);

-- 2. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_favorite_account_id ON public.favorite_vehicles(account_id);
CREATE INDEX IF NOT EXISTS idx_favorite_vehicle_id ON public.favorite_vehicles(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_favorite_priority ON public.favorite_vehicles(priority);
CREATE INDEX IF NOT EXISTS idx_favorite_created ON public.favorite_vehicles(created_at DESC);

-- 3. Price history table for tracking
CREATE TABLE IF NOT EXISTS public.price_history (
    history_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id INTEGER NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    old_price DECIMAL(10,2),
    new_price DECIMAL(10,2),
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    change_percentage DECIMAL(5,2)
);

-- 4. Email notifications queue
CREATE TABLE IF NOT EXISTS public.price_alerts (
    alert_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    vehicle_id INTEGER NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    old_price DECIMAL(10,2),
    new_price DECIMAL(10,2),
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. View for popular vehicles
CREATE OR REPLACE VIEW public.popular_vehicles_view AS
SELECT 
    i.inv_id,
    i.inv_make,
    i.inv_model,
    i.inv_year,
    i.inv_price,
    i.inv_thumbnail,
    COUNT(f.favorite_id) as favorite_count,
    ROUND(AVG(f.priority), 1) as avg_priority
FROM inventory i
LEFT JOIN favorite_vehicles f ON i.inv_id = f.vehicle_id
GROUP BY i.inv_id, i.inv_make, i.inv_model, i.inv_year, i.inv_price, i.inv_thumbnail
ORDER BY favorite_count DESC, avg_priority DESC;

-- 6. View for user favorites summary
CREATE OR REPLACE VIEW public.user_favorites_summary AS
SELECT 
    a.account_id,
    a.account_firstname,
    a.account_lastname,
    a.account_email,
    COUNT(f.favorite_id) as total_favorites,
    MAX(f.created_at) as last_favorite_date,
    ARRAY_AGG(DISTINCT i.inv_make) as favorite_makes
FROM account a
LEFT JOIN favorite_vehicles f ON a.account_id = f.account_id
LEFT JOIN inventory i ON f.vehicle_id = i.inv_id
GROUP BY a.account_id, a.account_firstname, a.account_lastname, a.account_email;

-- 7. Sample data for testing (optional)
-- INSERT INTO favorite_vehicles (account_id, vehicle_id, priority, notes)
-- VALUES 
--   (1, 1, 5, 'Dream car!'),
--   (1, 3, 4, 'Good family vehicle'),
--   (1, 5, 3, 'Fuel efficient');

-- 8. Check tables were created
SELECT 
    'favorite_vehicles' as table_name, 
    COUNT(*) as row_count 
FROM favorite_vehicles
UNION ALL
SELECT 
    'price_history', 
    COUNT(*) 
FROM price_history
UNION ALL
SELECT 
    'price_alerts', 
    COUNT(*) 
FROM price_alerts;