-- =============================================
-- CSE 340 - ASSIGNMENT 2 - DATABASE REBUILD
-- =============================================

-- Clean up existing database objects
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS classification CASCADE;
DROP TYPE IF EXISTS account_type CASCADE;

SELECT '=== DATABASE CLEANUP COMPLETE ===' as status;

-- Create the account_type ENUM
CREATE TYPE account_type AS ENUM ('Client', 'Employee', 'Admin');
SELECT '=== ACCOUNT_TYPE ENUM CREATED ===' as status;

-- Create account table
CREATE TABLE account (
    account_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR(50) NOT NULL,
    account_lastname VARCHAR(50) NOT NULL,
    account_email VARCHAR(100) NOT NULL,
    account_password VARCHAR(50) NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'
);
SELECT '=== ACCOUNT TABLE CREATED ===' as status;

-- Create classification table
CREATE TABLE classification (
    classification_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR(50) NOT NULL
);
SELECT '=== CLASSIFICATION TABLE CREATED ===' as status;

-- Create inventory table
CREATE TABLE inventory (
    inv_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INTEGER NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR(500) NOT NULL,
    inv_thumbnail VARCHAR(500) NOT NULL,
    inv_price DECIMAL(10,2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color VARCHAR(50) NOT NULL,
    classification_id INTEGER NOT NULL,
    FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
);
SELECT '=== INVENTORY TABLE CREATED ===' as status;

-- Insert sample classifications
INSERT INTO classification (classification_name) VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');
SELECT '=== CLASSIFICATION DATA INSERTED (5 categories) ===' as status;

-- Insert sample inventory data 
INSERT INTO inventory (
    inv_make, inv_model, inv_year, inv_description, 
    inv_image, inv_thumbnail, inv_price, inv_miles, 
    inv_color, classification_id
) VALUES
-- Sport vehicles (classification_id = 2) - 2 VEHICLES
('Chevy', 'Camaro', 2018, 'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 10122, 'Silver', 2),
('Ford', 'Mustang', 2020, 'Classic American muscle car with modern features and incredible performance.', '/images/mustang.jpg', '/images/mustang-tn.jpg', 32000, 8500, 'Red', 2),

-- Custom vehicles (classification_id = 1)
('Batmobile', 'Custom', 2021, 'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during your chase.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 2987, 'Black', 1),

-- SUV vehicles (classification_id = 3)
('GM', 'Hummer', 2016, 'Do you have 6 kids and like to go off-roading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 48563, 'Yellow', 3),

-- Sedan vehicles (classification_id = 5)
('Ford', 'Crown Victoria', 2013, 'After the police force updated their fleet these cars are now available to the public! These cars come equipped with the siren which is convenient if you are in an emergency.', '/images/crown-victoria.jpg', '/images/crown-victoria-tn.jpg', 25000, 25578, 'White', 5);
SELECT '=== INVENTORY DATA INSERTED (5 vehicles) ===' as status;

-- =============================================
-- TASK 1 QUERIES 4 & 6 (AUTO-APPLIED DURING REBUILD)
-- =============================================

-- TASK 1.4: Update GM Hummer description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';
SELECT '=== TASK 1.4 COMPLETE: Hummer description updated ===' as status;

-- TASK 1.6: Update image paths
UPDATE inventory 
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
SELECT '=== TASK 1.6 COMPLETE: Image paths updated ===' as status;

-- =============================================
-- FINAL VERIFICATION
-- =============================================

SELECT '=== DATABASE REBUILD COMPLETE ===' as final_status;

-- Verify all tables exist
SELECT 'Existing Tables:' as verification;
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' ORDER BY table_name;

-- Verify data counts
SELECT 'Data Counts:' as verification;
SELECT 
    (SELECT COUNT(*) FROM account) as account_count,
    (SELECT COUNT(*) FROM classification) as classification_count,
    (SELECT COUNT(*) FROM inventory) as inventory_count;

-- Verify Hummer description was updated
SELECT 'Hummer Description Check:' as verification;
SELECT inv_description FROM inventory 
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Verify image paths were updated
SELECT 'Image Paths Check (first 3 vehicles):' as verification;
SELECT inv_make, inv_model, inv_image, inv_thumbnail 
FROM inventory LIMIT 3;

-- VERIFY SPORT VEHICLES COUNT -
SELECT 'Sport Vehicles Count:' as critical_check;
SELECT COUNT(*) as sport_vehicle_count 
FROM inventory
INNER JOIN classification 
ON inventory.classification_id = classification.classification_id
WHERE classification_name = 'Sport';

-- SHOW THE ACTUAL SPORT VEHICLES
SELECT 'Actual Sport Vehicles:' as verification;
SELECT inv_make, inv_model, classification_name
FROM inventory
INNER JOIN classification 
ON inventory.classification_id = classification.classification_id
WHERE classification_name = 'Sport';